export * from './genres/Genres';
export * from './genre/Genre';
export * from './genre.detail/Genre.Detail';
export * from './genre.details/GenreDetails';
export * from './header/Header';
export * from './movies/Movies';
export * from './movie/Movie';
export * from './search.form/SearchForm';
export * from './search.movie/SearchMovie';